[versions]
kotlin = "2.3.0"
coroutines = "1.10.2"

# 1.8 and beyond switched to `all-compatibility` mode
# https://github.com/Kotlin/kotlinx.serialization/blob/master/CHANGELOG.md#generate-java-8s-default-method-implementations-in-interfaces
# this causes issues for extensions as some required generated classes are not in the final apk due to the library being compile only
# more info: https://github.com/keiyoushi/extensions-source/pull/12962#issuecomment-3828458599
serialization = "1.7.3"

[libraries]
gradle-agp = { module = "com.android.tools.build:gradle", version = "9.0.0" }
gradle-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradle-serialization = { module = "org.jetbrains.kotlin:kotlin-serialization", version.ref = "kotlin" }

spotless-gradle = { group = "com.diffplug.spotless", name = "spotless-plugin-gradle", version = "8.2.1" }

aniyomi-lib = { module = "com.github.komikku-app:aniyomi-extensions-lib", version = "F078000101" }

kotlin-protobuf = { module = "org.jetbrains.kotlinx:kotlinx-serialization-protobuf", version.ref = "serialization" }
kotlin-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }

coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }

injekt-core = { module = "com.github.null2264.injekt:injekt-core", version = "4135455a2a" }
jsoup = { module = "org.jsoup:jsoup", version = "1.22.1" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version = "5.3.2" }
quickjs = { module = "app.cash.quickjs:quickjs-android", version = "0.9.2" }
jsunpacker = { module = "dev.datlag.jsunpacker:jsunpacker", version = "1.0.2" }

[bundles]
common = ["coroutines-core", "coroutines-android", "injekt-core", "kotlin-protobuf", "kotlin-json", "jsoup", "okhttp", "aniyomi-lib", "quickjs"]
